### ISSUE TITLE
The package does not work on Node 7

### ISSUE THREAD

**Issue by Fohlen** [othiym23/toml-stream#2]
Trying to install the package from npm with Node 7 firstly results in an error:

```
> var toTOMLString = require('toml-stream').toTOMLString
Error: Cannot find module 'toml-stream'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at repl:1:20
    at realRunInThisContextScript (vm.js:22:35)
    at sigintHandlersWrap (vm.js:98:12)
    at ContextifyScript.Script.runInThisContext (vm.js:24:12)
    at REPLServer.defaultEval (repl.js:346:29)
    at bound (domain.js:280:14)
```
Further tracking this down by manually transpiling the package with `npm run transpile` gives the following on import:

```
var toTOMLString = require('toml-stream').toTOMLString
/Users/berger/workspace/test/node_modules/toml-stream/lib/toml-stream.js:5
import { encode, getTypeTag, getCodec } from './codecs/index.js';
^^^^^^
SyntaxError: Unexpected token import
```
I might be mistaken but shouldn't babel deliver for `CommonJS` in that case?

**Comment by Fohlen** [comment]
All tests run in `node11`. Closing.
